#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Apr 24 16:18:09 2026

@author: valenchonc
"""

import matplotlib.pyplot as plt
from math import exp
from ase.units import kB
import numpy as np
from scipy.ndimage import gaussian_filter1d
from scipy.interpolate import interp1d
import msd_module_openmp  # Importe le module compilé


# Taille de l'espace considéré
H = 100
L = 100
x0 = [50,50]
N=1000000

tpsVar=1        #si =0 tps constant, si =1 temps variable
swap=0          #activation du swap si 1, désactivation si 0

### Paramètres du système
# # L'ordre de grandeur pour les énergies de formation et de migration d'un défaut sont de l'ordre de 1eV (cf rapport de stage de Manon Dewynter)
G_M = 1.5 #eV = barrière d'énergie pour l'échange lacune / atome du réseau
# G_Mdef = 0.5 #eV = barrière d'énergie pour l'échange lacune / atome substitué
# G_F = 1.0 #eV = énergie libre de Gibbs de formation du défaut substitutionnel
T = 300 #K
nu_0 = 10e13


cDef = [0, 0.0001, 0.001, 0.01, 0.1, 0.5, 0.593]
freqAt = nu_0 * exp(-G_M/(kB*T))               #Fréquence de saut des atomes du réseau
alpha = [0.001, 0.01, 0.1, 1, 10, 100, 1000]


#Fonction calculant l'asymptote comme étant la valeur centrale du plus grand tube de diamètre val_courante*10%
def AsymptoteTube(y, eps): 
    valRes=0    #valeur de début du segment le plus long dans la plage [val-val*eps, val+val*eps]
    longRes=0   #longueur du segment le plus long    
    iRes=0
    
    for iDeb in range(len(y)):
        iP = iDeb      #pointeur courant
        compteur=0     #longueur du segment courant
        val=y[iDeb]
        
        while(iP<len(y)) and (y[iP]>val-val*eps) and (y[iP]<val+val*eps):
            compteur+=1
            if compteur>longRes:
                longRes=compteur
                valRes=y[iDeb]
                iRes=iDeb
            iP+=1
    
    return valRes, np.mean(y[iRes:iRes+longRes+1]), iRes    

def f(MSD, tau):
    d=1                                        #distance entre les noeuds du réseau
    w0=1                                       #fréquence de saut de base             
    Z=4                                        #nombre de plus proches voisins             
    D_rand = (1/Z) * d**2 * w0
    MSD_rand = 4*D_rand*tau                      
    return MSD/MSD_rand

# Definition de la fonction linéaire
def lineaire(t, x, y):
    return x + t*y


plt.close("all")
###  Récupération et exploitation des data  ###
eps=0.05
tau = 10        #nb de valeurs sur lesquelles est moyenné D
for a in alpha:
    for cD in cDef:
        data = np.load(f"Traj_swap_{swap}_tpsVariable_{tpsVar}_N_{N}_cD_{cD}_alpha_{a}.npz", allow_pickle=True)
        pos_reelle=data["pos_reelle"]
        positions=data["positions"]
        Densite=data["Densite"]
        listeDefauts=data["listeDefauts"]
        
        
        if tpsVar==1:
            temps=data["temps"]
        else:
            temps=np.array([i for i in range(N+1)])
       
        
        if swap==1:
            defautsFin=data["defautsFin"]
            defautsFin = defautsFin.item()  # Extrait le set du 0-d array
            defautsFin = list(defautsFin) 

        ### Calcul du MSD ###
        centresMSD, MSDLogVar, stdLogVar = msd_module_openmp.MSDLongueVar_openmp(pos_reelle, temps)  
        
        #Fitting curve_fit du MSD
        stdLogVar[stdLogVar == 0] = 1e-8
        
        
        nbDT = 1000
        
        ###  On interpole la courbe du MSD obtenu en échelle log-log en une courbe similaire en échelle linéaire, à pas réguliers dans l'espace réel
        log_dt = np.linspace(np.min(np.log(centresMSD)), np.max(np.log(centresMSD)), num=nbDT)        
        flog_MSD = interp1d(np.log(centresMSD), np.log(MSDLogVar), kind='quadratic')
        log_MSD=flog_MSD(log_dt)
        
        new_dt=np.linspace(log_dt.min(), log_dt.max(), nbDT)     #Abscisses linéairement réparties le long de l'axe log. Idem log_dt ?     
        
        #Calcul de la dérivée, interpolation et lissage de celle-ci
        deri_log = np.gradient(log_MSD, log_dt)       
        fderi_interp_log = interp1d(log_dt, deri_log, kind='quadratic')
        deri_interp_log = fderi_interp_log(new_dt)
        
        sigma=20
        deri_lisse = gaussian_filter1d(deri_interp_log, sigma=sigma, mode='nearest')
        
        #Calcul de la pente du log du MSD
        asympTubeDeb, asympTubeMean, longTube = AsymptoteTube(deri_lisse, eps)
        
        
        ### Calcul d'un D correct avec les pentes calculées ###
        fLog_Long = np.zeros(len(centresMSD))
        DLog_Long = np.zeros(len(centresMSD))               
        
        
        # Coefficient de diffusion et facteur de corrélation, calculé à t pour une fenêtre de MSD centrée en t et de largeur tau
        for ind in range(len(centresMSD)-tau//2):
            fLog_Long[ind] = np.mean(np.array([f(MSDLogVar[k],centresMSD[k]) for k in range(ind-tau//2, ind+tau//2, 1)]))
            DLog_Long[ind] = np.mean(np.array([MSDLogVar[k]/(4*(centresMSD[k])**asympTubeMean) for k in range(ind-tau//2, ind+tau//2, 1)]))
            
         
        _, D, debD = AsymptoteTube(DLog_Long, eps)
        _, fCor, debf = AsymptoteTube(fLog_Long, eps)
        print(f"Coefficient de diffusion obtenu pour cDef={cD} et alpha={a}: {D} pour un tube commencé à l'indice {debD}")
        print(f"Facteur de corrélation obtenu pour cDef={cD} et alpha={a}: {fCor} pour un tube commencé à l'indice {debf}")
        
        
        ###  Tracés  ###
        
        ax[0].plot(centresMSD, DLog_Long, '+', markersize=3, color = "red")
        ax[0].set_xlabel("dt (en secondes)", fontsize=11)
        ax[0].set_ylabel("D", fontsize=11)
        ax[0].set_title(f"D de la longue trajectoire en fonction de tau avec cDef = {cD} et alpha = {a} \nTemps de saut variable - D = {D}", fontsize=10)
        ax[0].set_xscale("log")
        ax[0].set_yscale("log")      
        ax[0].hlines(D, centresMSD.min(),  centresMSD.max(), color="firebrick")
        ax[1].plot(centresMSD, fLog_Long, '+', markersize=3, color = "blue")
        ax[1].hlines(fCor, centresMSD.min(),  centresMSD.max(), color="navy")
        ax[1].set_xlabel("dt (en secondes)", fontsize=11)
        ax[1].set_ylabel("D", fontsize=11)
        ax[1].set_title(f"f de la longue trajectoire en fonction de tau avec cDef = {cD} et alpha = {a}\nFréquence de saut variable", fontsize=10)
        ax[1].set_xscale("log")
        ax[1].set_yscale("log")
        ax[0].grid("on")
        ax[1].grid("on")
        fig.subplots_adjust(hspace = 0.7)     
        fig.savefig(f'D_f_swap_{swap}_tpsVar_{tpsVar}_N_{N}_cD_{cD}_alpha_{a}_sigma_{sigma}_eps_{eps}.png', dpi=300, bbox_inches='tight', pad_inches=0.1)   # save the figure to file
        plt.close(fig)    
        
        fig, ax = plt.subplots(2)
        ax[0].plot(centresMSD, MSDLogVar, 'o', markersize=2, color="midnightblue", label="MSD de référence")
        ax[0].plot(np.exp(log_dt), np.exp(log_MSD), color="orchid",ls='--',lw=1, label="Courbe interpolée")
        ax[0].plot(centresMSD, 4*D*(centresMSD)**asympTubeMean, color="greenyellow",ls='--',lw=1, label="Courbe avec D et exposant de la loi diffusion estimés")
        ax[0].set_xlabel("dt", fontsize=9)
        ax[0].set_ylabel("MSD", fontsize=9)
        ax[0].set_title(f"MSD de référence et interpolé pour cDef={cD} et alpha={a}\n sigma de l'interpolation = {sigma}, D={D} et exposant de la loi={asympTubeMean}", fontsize=9)
        ax[0].set_xscale("log")
        ax[0].set_yscale("log")
        ax[0].grid("on")       
        ax[1].plot(log_dt, deri_log, '+', markersize=1, color="black", label="dérivée selon dt du MSD interpolé")
        ax[1].plot(new_dt, deri_lisse, 'o', markersize=1, color="orchid", label="dérivée selon dt lissée du MSD interpolé")
        ax[1].set_xlabel("dt", fontsize=9)
        ax[1].set_ylabel("dérivée selon dt du MSD", fontsize=9)
        ax[1].hlines(asympTubeMean, np.min(new_dt), np.max(new_dt), label=f"Valeur convergée (moyenne tube) de la dérivée du MSD à {asympTubeMean}", ls='--', color="darkcyan")            
        ax[1].set_title(f"Dérivée du MSD selon dt et valeur convergée calculée par la méthode du tube pour un nombre d'abscisses\n d'interpolation du MSD nb_dt={nbDT}, sigma={sigma}, cDef={cD} et alpha={a} - Fréquence de saut variable", fontsize=9)
        ax[1].grid("on")
        ax[0].legend(loc = 'best', fontsize = 6) 
        ax[1].legend(loc = 'best', fontsize = 6) 
        fig.subplots_adjust(hspace = 0.5) 
        fig.savefig(f"Dérivée_swap_MSD_Méthode_Tube_tolerance_{eps}_nbDt_{nbDT}_N_{N}_cD_{cD}_alpha_{a}_sigma_{sigma}.png", dpi=300, bbox_inches='tight', pad_inches=0.1)        
        plt.close(fig)
        
        fig, ax = plt.subplots()
        abscisses = [elem[0] for elem in positions]
        ordonnees = [elem[1] for elem in positions]
        ax.scatter(abscisses, ordonnees, c=range(len(abscisses)), cmap='viridis')
        ax.set_xlabel("positions X", fontsize=11)
        ax.set_ylabel("positions Y", fontsize=11)
        ax.set_title(f"Marche aléatoire avec cDef = {cD} et alpha = {a} \nFréquence de saut variable", fontsize=11)
        fig.savefig(f'Marche_swap_tps_var_N_{N}_cD_{cD}_alpha_{a}_sigma_{sigma}_eps_{eps}.png', dpi=300, bbox_inches='tight', pad_inches=0.1)   # save the figure to file
        plt.close(fig)   
        
        Densite[Densite == 0] = 1e-8        #pour éviter log(0)
        fig, ax = plt.subplots()
        im = ax.imshow(np.log(Densite.T), cmap='plasma', origin='lower')
        fig.colorbar(im, ax=ax, label="log(Densité de passage)")
        ax.set_xlabel('X', fontsize=9)
        ax.set_ylabel('Y', fontsize=9)
        
        ax.set_title(f"Mapping de la densité de passage pour alpha ={a}, concentration de défauts = {cD}\n et position initiale {x0}\nFréquence de saut variable", fontsize=9)
        ax.tick_params(axis='both', labelsize=11)
        
        XDisplay = []
        YDisplay = []
        for (aDef,bDef) in listeDefauts:
            XDisplay.append(aDef)
            YDisplay.append(bDef)
        plt.plot(XDisplay, YDisplay, "x", markersize=2, color="dodgerblue", label='Positions initiales défauts',alpha=0.6) 
            
        if swap==1:  
            XDefCourant = []
            YDefCourant = []
            for (aD,bD) in defautsFin:
                XDefCourant.append(aD)
                YDefCourant.append(bD)
            plt.plot(XDefCourant, YDefCourant, "^", markersize=2, color="firebrick", label='Positions finales défauts', alpha=0.6)
        
        plt.legend(prop={'size':8}, loc='lower left')
        fig.savefig(f'Densite_swap_tps_var_N_{N}_cD_{cD}_alpha_{a}_sigma_{sigma}_eps_{eps}.png', dpi=300, bbox_inches='tight', pad_inches=0.1)
        plt.close(fig)   
        

        
